# configs of the market
traderNumber: 3
sellerNumber: 3
buyerNumber: 3
port: 2121
deployOnSingleComputer: false
sleepBeforeStart: 30000
numberOfTests: 20


maxmumStok: 100
productNameList:
  - Fish
  - Salt
  - Boar



# config of runner
rpcBuffSize: 10240
runMode: 0

# not use any more
neighbourNum: 1
maxJump: 5