version: "3.3"
services:
    couchdb:
        image: couchdb
        ports:
            - "5984:5984"
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=passWd
        container_name: couchdb.service
    cs677.lab2.peer5.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer5.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer5.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
    cs677.lab2.peer4.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer4.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer4.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
    cs677.lab2.peer2.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer2.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer2.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
    cs677.lab2.peer3.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer3.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer3.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
    cs677.lab2.peer1.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer1.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer1.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
    cs677.lab2.peer0.example.com:
        build: .
        volumes:
            - ./cs677.lab2.peer0.example.com:/app
        working_dir:
            /app
        container_name: cs677.lab2.peer0.example.com
        depends_on:
            - couchdb
        tty: true
        command: [ "./wait-for.sh", "couchdb.service:5984", "--", "sh", "start.sh" ]
